- name: Install System Packages 1 (build-essential)
  become: true
  apt:
    name: ["build-essential", "make"]
  tags:
    - install
    - core

- name: Install System Packages 2 (Neovim build prerequisites)
  become: true
  apt:
    name: ["clang", "gcc", "ninja-build", "gettext", "cmake", "unzip", "curl", "ripgrep"]
  tags:
    - install
    - neovim
    - core
