- name: Install Core Packages 1 (build-essential and make)
  become: true
  apt:
    name: ["build-essential", "make"]
  tags:
    - install
    - core

- name: Install Core Packages 2 (Neovim build prerequisites)
  become: true
  apt:
    name: ["clang", "gcc", "ninja-build", "gettext", "cmake", "unzip", "curl", "ripgrep"]
  tags:
    - install
    - neovim
    - core

- name: Install Core Packages 3 (go)
  become: true
  apt:
    name: ["golang-go"]
  tags:
    - install
    - go
