- name: Check that the n location exists
  stat:
    path: /home/joe/.local/n
  register: n_stats
  tags: &tags_for_n_tasks [ 'install', 'node', 'npm', 'n' ]

- name: Install n with n-install
  shell: curl -L https://raw.githubusercontent.com/mklement0/n-install/stable/bin/n-install > ~/.n-install && chmod +x ~/.n-install && N_PREFIX=~/.local/n ~/.n-install -y
  tags: *tags_for_n_tasks
  when: n_stats.stat.exists == False
  become_user: joe

- name: Install correct version of Node
  shell: n 18
  tags: *tags_for_n_tasks
