- name: Install
  become: true
  apt:
    name: [ "tmux" ]
  tags:
    - install
    - productivity
    - tmux
- name: Clone TPM
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm.git'
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
  tags:
    - install
    - productivity
    - tmux
- name: Install some additional useful packages
  become: true
  apt:
    name: [ "xclip", "htop", "tree" ]
  tags:
    - install
    - productivity

